using UnityEngine;
using UnityEngine.SceneManagement;
using System.Threading;

public class TeleportBack : MonoBehaviour, IInteractable
{
    public string GetDescription()
    {
        return "Teleport back to the main game!";
    }

    public void Interact()
    {
        SceneManager.LoadScene("MainScene");
        Time.timeScale = 0;
        var Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.Find("Player");
        Player = GameObject.FindWithTag("Player");
        Time.timeScale = 1;
        Player.SetActive(true);
    }
}